### ISSUE TITLE
how many trips did each service make in 2015?

### ISSUE THREAD

**Issue by beanumber** [liwencong1995/SDS430D-Honors-Project-2017-2018#3]

**Comment by liwencong1995** [comment]
Yellow Taxi: 195267408 (144291905)
Green Taxi: 
Uber 2014: sqlite: 4534327 (mysql: 4388535)
Uber 2015: sqlite: 14270479 (mysql: 14207386)
Lyft:15795

**Comment by liwencong1995** [comment]
created a summary table and visualizations for all transportations' data from 2014 to 2016.
